resources:
  - type: package
    name: git
  - type: package
    name: ruby
  - type: package
    name: base-devel
    options: '--needed'
    check_script: pacman -Q gcc
  - type: git
    repository: https://github.com/hanachin/yamamayaa.git
    path: /home/sei/yamamayaa
    status: updated
    user: sei
  - type: command
    check_script: 'gem list | grep bundler'
    script: gem install bundler
    user: sei
  - type: command
    cwd: /home/sei/yamamayaa
    script: "`ruby -e 'print Gem.user_dir'`/bin/bundle install --path=vendor/bundle"
    user: sei
  - type: symlink
    destination: /home/sei/yamamayaa/.irkit.json
    source: /home/sei/.irkit.json
    user: sei
