resources:
  - type: rbenv_dependent_packages
  - type: rbenv_ruby
    version: 2.4.1
    user: sei
    dependencies: true
    profile_path: /home/sei/.bashrc
  - type: package
    name: git
  - type: git
    repository: https://github.com/hanachin/yamamayaa.git
    path: /home/sei/yamamayaa
    state: updated
    user: sei
  - type: command
    check_script: 'gem list | grep bundler'
    script: gem install bundler
    user: sei
  - type: command
    cwd: /home/sei/yamamayaa
    script: "bundle install --path=.bundle"
    user: sei
  - type: symlink
    destination: /home/sei/yamamayaa/.irkit.json
    source: /home/sei/.irkit.json
    user: sei
  - type: command
    cwd: /home/sei/yamamayaa
    script: "bundle exec whenever -w"
    user: sei
  - type: command
    cwd: /opt
    script: wget -O node-v8.1.3-linux-armv6l.tar.gz https://nodejs.org/dist/v8.1.3/node-v8.1.3-linux-armv6l.tar.gz && tar -xzf node-v8.1.3-linux-armv6l.tar.gz && mv node-v8.1.3-linux-armv6l nodejs && rm node-v8.1.3-linux-armv6l.tar.gz && ln -s /opt/nodejs/bin/node /usr/bin/node && ln -s /opt/nodejs/bin/npm /usr/bin/npm
    check_script: which npm
